# dev_dependency is set to True.  This module will not be included in any JS bundle or JVM binary.
node_module(
  sources=['package.json', 'web-build-tool', 'webpack.config.base.js'],
  dependencies=[
    '3rdparty/node/babel-loader',
    '3rdparty/node/css-loader',
    '3rdparty/node/null-loader',
    '3rdparty/node/style-loader',
    '3rdparty/node/webpack',
  ],
  dev_dependency=True,
)
